services:
  home_assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./ha_integrations:/config/custom_components
      - ./ha_conf:/config
    environment:
      - TZ=MY_TIME_ZONE
    restart: unless-stopped
    ports:
      - 8123:8123
#    networks:
#      - default

  simple_light:
    build:
      context: .
      dockerfile: docker/DockerfileLight
    ports:
      - 8001:4444

  tg_bot:
    build:
      context: .
      dockerfile: docker/DockerfileTg
#    networks:
#      - default

#    message_source:
#      image:
#    networks:


#networks:
#  default:
#    name: default