services:
  home_assistant:
    build:
      context: .
    volumes:
      - ./ha_integrations:/config/custom_components
      - ./ha_conf:/config
      - audio_files:/voice_messages
    environment:
      - TZ=MY_TIME_ZONE
    restart: unless-stopped
    ports:
      - 8123:8123
    depends_on:
      - simple_light
    networks:
      iot_network:
#        ipv4_address: 172.16.238.2
      default:

  simple_light:
    build:
      context: .
      dockerfile: simple_console_light/Dockerfile
    ports:
      - 8001:80
    networks:
      iot_network:
      default:

  simple_light2:
    build:
      context: .
      dockerfile: simple_console_light/Dockerfile
#    ports:
#      - 8002:80
    networks:
      iot_network:
      default:

  simple_light3:
    build:
      context: .
      dockerfile: simple_console_light/Dockerfile
#    ports:
#      - 8003:80
    networks:
      iot_network:
      default:

  tg_bot:
    build:
      context: .
      dockerfile: tg_bot/Dockerfile
    image: tg_bot_for_iot
    volumes:
      - audio_files:/voice_messages
    networks:
      iot_network:
      default:
    environment:
      - KEY_PHASE=
    depends_on:
      - simple_light


networks:
  iot_network:
    name: iot_network
    driver: bridge
    internal: true
#    ipam:
#     driver: default
#     config:
#       - subnet: 172.16.238.0/24
#         gateway: 172.16.238.1

#  default:
#    driver: bridge
#    external: True

volumes:
  audio_files:
