services:
  home_assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./ha_integrations:/config/custom_components
      - ./ha_conf:/config
    environment:
      - TZ=MY_TIME_ZONE
    restart: unless-stopped
    ports:
      - 8123:8123
    depends_on:
      - simple_light
    networks:
      iot_network:
#        ipv4_address: 172.16.238.2
      default:

  simple_light:
    build:
      context: .
      dockerfile: docker/DockerfileLight
    ports:
      - 8001:4444
    networks:
      iot_network:
#        ipv4_address: 172.16.238.2
      default:


networks:
  iot_network:
    name: iot_network
    driver: bridge
    internal: true
#    ipam:
#     driver: default
#     config:
#       - subnet: 172.16.238.0/24
#         gateway: 172.16.238.1

#  default:
#    driver: bridge
#    external: True
