[tool.poetry]
name = "speechrecognizer"
version = "0.1.0"
description = ""
authors = ["ewasince <ewasince@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
speechrecognition = "^3.10.0"
google-cloud-speech = "^2.21.0"
pyaudio = "^0.2.13"
apscheduler = "^3.10.4"
pydantic = "^2.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
